### ISSUE TITLE
general inquiry 

### ISSUE THREAD

**Issue by Spamiad** [takemasa-miyoshi/letkf#3]
Dear takemasa-miyoshi,

could you please confirm that this is the kalman gain matrix?
https://github.com/takemasa-miyoshi/letkf/blob/master/common/common_letkf.f90#L204

Very appreciated!

**Comment by gylien** [comment]
Sorry for the late reply.  That is the gain to update the multiplicative inflation parameter with the adaptive inflation scheme (Miyoshi 2011, MWR), not the Kalman gain matrix for data assimilation.  In LETKF, the Kalman gain matrix is not explicitly calculated.

Guo-Yuan

**Comment by Spamiad** [comment]
Hello, thanks for the answer. It is clear to me now, I was new to the topic.

May I ask if putting some loops in parallel in common_letkf.f90 might increase performance?
Or would the overhead be too large for these operations.

**Comment by gylien** [comment]
You can try.  I do not have an answer.  In most of the code in this repository, we use MPI+OpenMP outside of the common_letkf.f90, so we'd like to run the code in common_letkf.f90 only in a single thread.
